live_config_reload = true

shell = "fish"

import = [
    "~/.config/alacritty/themes/github_light.toml"
]

[window]
dynamic_padding = true
opacity = 1.00

[font]
normal = { family = "Comic Code", style = "Regular" }
offset = {x = 0, y = 1}
glyph_offset = { x = 0, y = 2 }
builtin_box_drawing = false

[colors]
vi_mode_cursor = { text = "#000000", cursor = "#ffffff" }
cursor = { text = "#ffffff", cursor = "#000000" }

[mouse]
hide_when_typing = true
