live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

[env]
# This makes it so that tmux can use true colors
TERM = 'xterm-256color'

[window]
dynamic_padding = true
opacity = 1.00

[font]
normal = { family = "Comic Code", style = "Regular" }
offset = {x = 0, y = 0}
glyph_offset = { x = 0, y = 2 }
builtin_box_drawing = false

[colors]
vi_mode_cursor = { text = "#ffffff", cursor = "#000000" }
cursor = { text = "#ffffff", cursor = "#000000" }

[mouse]
hide_when_typing = true
