#!/bin/sh

path=$1
message=$2
branch=$3

if [ -z "$path" ] || [ -z "$branch" ]; then
    echo "Usage: $0 <path> <message> <branch>"
    exit 1
fi

if [ -z "$message" ]; then
    temp_file=$(mktemp)
    nvim "$temp_file"
    message=$(cat "$temp_file")
    rm "$temp_file"
fi

git add "$path"
git commit -m "$message"
git push origin "$branch"
