#! /bin/sh
sxhkd &
picom -b --experimental-backends &
flameshot &
dunst &
lxpolkit &
launchpolybar &
xset r rate 150 20 &
xrandr --output DVI-D-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-2 --primary --mode 1920x1080 --refresh 165.00 --pos 0x0 --rotate normal --output DP-2 --off --output HDMI-1 --off --output HDMI-2 --off &

# Make accell profile flat
exec xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1 &
exec xinput --set-prop 10 'libinput Accel Profile Enabled' 0, 1 &
exec xinput --set-prop 12 'libinput Accel Profile Enabled' 0, 1 &
exec xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1 &
exec xinput --set-prop 15 'libinput Accel Profile Enabled' 0, 1 &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10
