#+title: Summer notes
#+author: Gustavo Meireles

* WEB
** Ruby on rails                                                          :ruby:
*** A Web App is divided into three parts:
    + Model
    + View
    + Controller
**** This Provides a good division of concerns.

** RUBY
*** Pgn file Parser
    I intend to create a pgn file parser that can understand chess notation.
    It will be programmed in ruby for my personal website


* UNIX                                                                    :unix:
** XTerm                                                                 :xterm:
*** Synopsis
    XTerm is a terminal emulator that was created for the X window system, it's the
    fastest terminal emulator there is and unfortunately wayland does not have
    a good alternative lmao. I really don't understand how they were this good
    at programming back in the 90's bro. They create linux, vim and xterm.
    I hope I can be a programmer as good as they were one day.

** Linux                                                                 :linux:
*** Synopsis
    Linux is an open source kernel used by people to make open source operating
    systems know as "distros" or "distributions".
**** Distros
***** Fedora
      + My main distribution for working. It's stable but has very modern packages.
***** Debian
      + Very stable distro good for servers.
***** Arch
      + Extremely modern packages, it frequently breaks because of this.


* Java
** Chess-App
   DEADLINE: <2023-09-01 Fri>
   An app that lets you play over the board chess
*** TODO Move solver
*** TODO possible move calculation per position
*** DONE figure out how the app works fundamentaly
    CLOSED: [2023-08-12 Sat 18:33]
*** Pieces
    + Pawn
    + Knight
    + Bishop
    + Rook
    + King
    + Queen
*** Board
    + Logic for setting up the board for the game
      - Square
      - Board
*** Parser
    + Logic for parsing *pgn* files and understanding *chess notation*
